# D:/git-repos/experiments/vlcpp-compile-test/mct_user_toolchain.cmake
# Project toolchain file generated by MCT. 
# DO NOT EDIT! ALL CHANGES WILL BE OVERRIDDEN!
# =======================================================================================================

# Local toolchain:
include(D:/tools/mct/vcpkg/scripts/buildsystems/vcpkg.cmake) #-local-toolchain
set(LOCAL_TRIPLET_INCLUDE_DIR D:/tools/mct/vcpkg/installed/${VCPKG_TARGET_TRIPLET}/include) #-local-include
include_directories(${LOCAL_TRIPLET_INCLUDE_DIR})

# User Toolchain Values:

# Project Shared Includes:

# Private Includes:
